web:
  image: alexcheng/magento
  ports:
    - "12345:80"
  volumes:
    - ./html:/var/www/htdocs
  links:
    - mysql
    - redis
  env_file:
    - env
mysql:
  image: mysql:5.6
  env_file:
    - env
redis:
  image: redis
 
